# http://materialdesignicons.com/cdn/7.4.47/

# Define icons used
font:
  - file: 'https://github.com/Templarian/MaterialDesign-Webfont/raw/v7.4.47/fonts/materialdesignicons-webfont.ttf'
    id: icon_font
    size: 40
    bpp: 4
    glyphs: [
      "\U000F0335",  # mdi-lightbulb
      "\U000F042B",  # mdi-printer-3d
      "\U000F0D43",  # mdi-air-filter
      "\U000F1051",  # mdi-led-strip-variant
      "\U000F03D7",  # mdi-package-variant-closed
      "\U000F07D6",  # mdi-led-strip
      "\U000F00AC",  # mdi-blinds-closed
      "\U000F1011",  # mdi-blinds-open
      "\U000F1A4C",  # mdi-lightbulb-night
      "\U000F1087",  # mdi-router-network
      "\U000F036B",  # mdi-message-video
      "\U000F0614",  # mdi-application-outline
      "\U000F0141",  # mdi-chevron-left
      "\U000F0143",  # mdi-chevron-up
      "\U000F0140",  # mdi-chevron-down
      "\U000F089E",  # mdi-battery
      "\U000F07DE",  # mdi-filament
      "\U000F0317",  # mdi-lan
      "\U000F0425",  # mdi-power
      "\U000F1798",  # mdi-fan-light
      "\U000F1846",  # mdi-curtains-open
      "\U000F1847",  # mdi-curtains-closed
      "\U000F0210",  # mdi-fan
      "\U000F081D",  # mdi-fan-off
      "\U000F1472",  # mdi-fan-speed-1
      "\U000F1473",  # mdi-fan-speed-2
      "\U000F1474",  # mdi-fan-speed-3
      "\U000F146E",  # mdi-fan-chevron-up
      "\U000F146F",  # mdi-fan-plus
      "\U000F1797",  # mdi-ceiling-fan
      "\U000F0792",  # arrow-collapse-down
      "\U000F0522",  # toggle-switch-off
      "\U000F04DE",  # stove
      "\U000F0454",  # remote
      ]

# Map icons to names
substitutions:
  lightbulb:      "\U000F0335"
  printer:        "\U000F042B"
  aircon:         "\U000F0D43"
  ledstrip:       "\U000F1051"
  led_strip_variant: "\U000F1051"
  package:        "\U000F03D7"
  lights:         "\U000F07D6"
  blinds_closed:  "\U000F00AC"
  blinds_open:    "\U000F1011"
  nightlight:     "\U000F1A4C"
  network:        "\U000F1087"
  videocall:      "\U000F036B"
  application:    "\U000F0614"
  chevron_left:   "\U000F0141"
  chevron_up:     "\U000F0143"
  chevron_down:   "\U000F0140"
  battery:        "\U000F089E"
  filament:       "\U000F07DE"
  lan:            "\U000F0317"
  power:          "\U000F0425"
  fan_light:      "\U000F1798"
  curtain_closed: "\U000F1847"
  curtain_open:   "\U000F1846"
  fan:            "\U000F0210"
  fan_off:        "\U000F081D"
  fan_speed_1:    "\U000F1472"
  fan_speed_2:    "\U000F1473"
  fan_speed_3:    "\U000F1474"
  fan_chevron_up: "\U000F146E"
  fan_plus:       "\U000F146F"
  ceiling_fan:    "\U000F1797"
  arrow_collapse_down: "\U000F0792"
  toggle_switch_off: "\U000F0522"
  stove:          "\U000F04DE"
  remote:         "\U000F0454"
