# =============================================================================
# SENSORS - Home Assistant State Synchronization
# =============================================================================
# This file creates sensors that monitor Home Assistant entities and update
# the touchscreen buttons to reflect the current state of your smart devices.
#
# WHY THIS FILE EXISTS:
# When you press a button on the touchscreen, it sends a command to Home
# Assistant. But what if someone turns on a light using their phone, or a
# scene activates automatically? This file ensures the touchscreen display
# always shows the ACTUAL state of each device, not just what was last pressed.
#
# HOW IT WORKS:
# 1. Each sensor subscribes to a Home Assistant entity (switch, sensor, etc.)
# 2. When that entity's state changes, the "on_state" or "on_value" trigger fires
# 3. The trigger updates the corresponding button in lvgl.yaml to show the new state
#
# KEY CONCEPTS:
# - "platform: homeassistant" = reads state directly from Home Assistant
# - "platform: template" = calculates a value using code (lambda)
# - "entity_id:" = the Home Assistant device/entity to monitor
# - "id:" = unique name to reference this sensor elsewhere in ESPHome
# - "trigger_on_initial_state: true" = update button immediately when device boots
# - "lvgl.widget.update" = changes how a button looks on screen
# - "checked: !lambda return x;" = x is the sensor's boolean state (true/false)
#
# RELATIONSHIP TO lvgl.yaml:
# Each sensor here has a matching button in lvgl.yaml:
#   - This file READS state from Home Assistant → updates button appearance
#   - lvgl.yaml SENDS commands to Home Assistant → when button is pressed
# =============================================================================


# =============================================================================
# REGULAR SENSORS (Numeric Values)
# =============================================================================
# These sensors read numeric values like temperature and position.
# They're used to display information or calculate other states.
# =============================================================================

sensor:

  # ===========================================================================
  # SENSOR: Office Temperature (Indoor)
  # ===========================================================================
  # WHAT IT MONITORS:
  #   The temperature inside the office from sensor.office_temperature
  #   (This could be from a smart thermostat, dedicated sensor, etc.)
  #
  # WHAT IT UPDATES:
  #   The "temperatures" label in the top-left corner of the screen
  #   Format: "outdoor° / indoor°" (e.g., "15° / 22°")
  #
  # HOW IT WORKS:
  #   When the office temperature changes in Home Assistant, this sensor
  #   receives the new value and updates the label text. It combines the
  #   outdoor temperature (from the other sensor below) with this value.
  #
  # RELATED UI ELEMENT:
  #   lvgl.yaml → temperatures label (id: temperatures)
  # ===========================================================================
  - platform: homeassistant
    entity_id: sensor.air_quality_monitor_temperature
    id: lounge_temperature
    on_value:
      - lvgl.label.update:
          id: temperatures
          text:
            format: "%d° / %d°"
            args: [ '(int)round(id(openweathermap_temperature).state)', '(int)round(x)' ]

  # ===========================================================================
  # SENSOR: Outdoor Temperature
  # ===========================================================================
  # WHAT IT MONITORS:
  #   The temperature outside from sensor.outdoor_temperature
  #   (This could be from a weather service, outdoor sensor, etc.)
  #
  # WHAT IT UPDATES:
  #   The "temperatures" label in the top-left corner of the screen
  #   Format: "outdoor° / indoor°" (e.g., "15° / 22°")
  #
  # HOW IT WORKS:
  #   When the outdoor temperature changes in Home Assistant, this sensor
  #   receives the new value and updates the label text. It combines this
  #   value with the office temperature (from the sensor above).
  #
  # NOTE: Both temperature sensors update the same label. Either one changing
  #       will refresh the display with both current values.
  #
  # RELATED UI ELEMENT:
  #   lvgl.yaml → temperatures label (id: temperatures)
  # ===========================================================================
  - platform: homeassistant
    entity_id: sensor.openweathermap_temperature
    id: openweathermap_temperature
    on_value:
      - lvgl.label.update:
          id: temperatures
          text:
            format: "%d° / %d°"
            args: [ '(int)round(x)', '(int)round(id(lounge_temperature).state)' ]

  # ===========================================================================
  # SENSOR: Curtain Robot - Bedroom
  # ===========================================================================
  # WHAT IT MONITORS:
  #   The current position of the bedroom curtain robot (0-100%)
  #   Reads the "current_position" attribute from cover.curtain_robot_bedroom
  #
  # WHAT IT'S USED FOR:
  #   This sensor doesn't directly update buttons. Instead, it provides
  #   the position value that the template sensors below use to determine
  #   which blind button should be highlighted.
  #
  # WHY IT'S SEPARATE:
  #   The blind has 4 preset buttons (0%, 33%, 66%, 100%), but the blind
  #   could be at ANY position. This sensor stores the actual position,
  #   and the template sensors below check if it's "close enough" to each
  #   preset (within 3%) to highlight that button.
  #
  # RELATED UI ELEMENTS:
  #   lvgl.yaml → curtain_robot_bedroom_open_button, curtain_robot_bedroom_close_button
  # ===========================================================================
  - platform: homeassistant
    entity_id: cover.curtain_bedroom_door
    id: curtain_robot_bedroom_position
    attribute: current_position

# =============================================================================
# BINARY SENSORS (On/Off States)
# =============================================================================
# These sensors track on/off states and update button appearances.
# When the sensor is ON (true), the button shows as "checked" (highlighted).
# When the sensor is OFF (false), the button shows as unchecked (dimmed).
# =============================================================================

binary_sensor:

  # ===========================================================================
  # Script: Light Fan
  # ===========================================================================
  - platform: homeassistant
    id: bedroom_light_fan
    entity_id: script.bedroom_light_fan
    trigger_on_initial_state: false
    on_state:
      then:
        - lvgl.widget.update:
            id: bedroom_fan_button
            state:
              checked: !lambda return x;

  # ===========================================================================
  # SENSOR: Lounge Ceiling Light State
  # ===========================================================================
  # WHAT IT MONITORS:
  #   Whether the Lounge Ceiling Light is turned on or off
  #   Watches: script.lounge_light_toggle in Home Assistant
  #
  # WHAT IT UPDATES:
  #   The "Ceiling" button's visual state (highlighted when running)
  #
  # RELATED UI ELEMENT:
  #   lvgl.yaml → lounge_light_button
  # ===========================================================================
  - platform: homeassistant
    id: bedroom_fan_light_toggle
    entity_id: script.bedroom_light_toggle
    trigger_on_initial_state: true
    on_state:
      then:
        - lvgl.widget.update:
            id: bedroom_fan_light_button
            state:
              checked: !lambda return x;
        - lvgl.widget.update:
            id: bedroom_fan_light_icon
            hidden: !lambda return x;
            
  # ===========================================================================
  # TEMPLATE SENSOR: Curtain at 100% (Fully Open)
  # ===========================================================================
  # WHAT IT DOES:
  #   Calculates whether the blind is at (or very close to) 100% open
  #   Returns TRUE if position is within 3% of 100, FALSE otherwise
  #
  # WHY USE A TEMPLATE:
  #   The curtain motor may not stop at exactly 100%. It might be 99% or 101%.
  #   This template uses a 3% tolerance to account for this imprecision.
  #   If position is between 97-100%, we consider it "fully open".
  #
  # HOW THE CODE WORKS:
  #   1. Check if curtain_robot_bedroom_position has received a value yet
  #   2. Calculate: |current_position - 100| <= 3
  #   3. Return true if within range, false otherwise
  #
  # WHAT IT UPDATES:
  #   The "Open" button's visual state (highlighted when blind is ~100%)
  #
  # RELATED UI ELEMENT:
  #   lvgl.yaml → curtain_robot_bedroom_open_button
  # ===========================================================================
  - platform: template
    id: curtain_robot_bedroom_100
    lambda: |-
      if (id(curtain_robot_bedroom_position).has_state()) {
        return abs(id(curtain_robot_bedroom_position).state - 100) <= 3;
      }
      return false;
    on_state:
      then:
        lvgl.widget.update:
          id: curtain_robot_bedroom_open_button
          state:
            checked: !lambda return x;

  # ===========================================================================
  # TEMPLATE SENSOR: Curtain at 0% (Fully Closed)
  # ===========================================================================
  # WHAT IT DOES:
  #   Calculates whether the blind is at (or very close to) 0% (closed)
  #   Returns TRUE if position is within 3% of 0, FALSE otherwise
  #
  # HOW THE CODE WORKS:
  #   Same logic as above, but checks for 0% (range: 0-3%)
  #
  # WHAT IT UPDATES:
  #   The "Close" button's visual state (highlighted when blind is ~0%)
  #
  # RELATED UI ELEMENT:
  #   lvgl.yaml → curtain_robot_bedroom_close_button
  # ===========================================================================
  - platform: template
    id: curtain_robot_bedroom_0
    lambda: |-
      if (id(curtain_robot_bedroom_position).has_state()) {
        return abs(id(curtain_robot_bedroom_position).state - 0) <= 3;
      }
      return false;
    on_state:
      then:
        lvgl.widget.update:
          id: curtain_robot_bedroom_close_button
          state:
            checked: !lambda return x;
  
  # ===========================================================================
  # SENSOR: Bedroom Lights State
  # ===========================================================================
  # WHAT IT MONITORS:
  #   Whether the office storage area lights are on or off
  #   Watches: light.office_storage in Home Assistant
  #
  # WHAT IT UPDATES:
  #   The "Desk Lights" button's visual state (highlighted when on)
  #
  # NOTE: This sensor references a button (desk_lights_button) that
  #       should be defined in lvgl.yaml. If the button doesn't exist,
  #       add it there or remove this sensor.
  #
  # RELATED UI ELEMENT:
  #   lvgl.yaml → storage_lights_button
  # ===========================================================================
  - platform: homeassistant
    id: bedroom_lights
    entity_id: light.switch_bedroom_light
    trigger_on_initial_state: true
    on_state:
      then:
        lvgl.widget.update:
          id: bedroom_lights_button
          state:
            checked: !lambda return x;

  # ===========================================================================
  # SENSOR: LED Dimmer - Bedroom Bed State
  # ===========================================================================
  # WHAT IT MONITORS:
  #   Whether the network rack lights are on or off
  #   Watches: llight.led_dimmer_bedroom_bed in Home Assistant
  #
  # WHAT IT UPDATES:
  #   The "Bed LED" button's visual state (highlighted when on)
  #
  # NOTE: This sensor references a button (led_dimmer_bedroom_bed_lights_button) that
  #       should be defined in lvgl.yaml. If the button doesn't exist,
  #       add it there or remove this sensor.
  #
  # RELATED UI ELEMENT:
  #   lvgl.yaml → led_dimmer_bedroom_bed_button
  # ===========================================================================
  - platform: homeassistant
    id: led_dimmer_bed_lights
    entity_id: light.led_dimmer_bed
    trigger_on_initial_state: true
    on_state:
      then:
        lvgl.widget.update:
          id: led_dimmer_bed_button
          state:
            checked: !lambda return x;

  # ===========================================================================
  # Automation: RM4 Mini Lounge IR
  # ===========================================================================
  # RELATED UI ELEMENT:
  #   lvgl.yaml → RM4 Mini
  # ===========================================================================
  - platform: homeassistant
    id: rm4_mini_lounge_sensor
    entity_id: binary_sensor.rm4_mini_lounge_toggle
    trigger_on_initial_state: false
    on_state:
      then:
        lvgl.widget.update:
          id: rm4_mini_lounge_button
          state:
            checked: !lambda return x;
